<?xml version="1.0" encoding="utf-8"?><Database Name="LibMan" Class="LibManDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=FAVIN;Initial Catalog=LibMan;Integrated Security=True" SettingsObjectName="DTO.Properties.Settings" SettingsPropertyName="LibManConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="Username" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fullname" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ID" Type="System.String" DbType="Char(12)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Account_Loan" Member="Loans" ThisKey="Username" OtherKey="Username" Type="Loan" />
      <Association Name="Role_Account" Member="Role" ThisKey="RoleID" OtherKey="ID" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Book" Member="Books">
    <Type Name="Book">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Catalog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Author" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Publisher" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Book_Loan" Member="Loans" ThisKey="ID" OtherKey="BookID" Type="Loan" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Association Name="Role_Account" Member="Accounts" ThisKey="ID" OtherKey="RoleID" Type="Account" />
    </Type>
  </Table>
  <Table Name="dbo.Loan" Member="Loans">
    <Type Name="Loan">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="BookID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LoanDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DueDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Loan_Returned" Member="Returneds" ThisKey="ID" OtherKey="LoanID" Type="Returned" />
      <Association Name="Book_Loan" Member="Book" ThisKey="BookID" OtherKey="ID" Type="Book" IsForeignKey="true" />
      <Association Name="Account_Loan" Member="Account" ThisKey="Username" OtherKey="Username" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Returned" Member="Returneds">
    <Type Name="Returned">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LoanID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Fine" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Loan_Returned" Member="Loan" ThisKey="LoanID" OtherKey="ID" Type="Loan" IsForeignKey="true" />
    </Type>
  </Table>
</Database>